### PR TITLE
Fix pop_local_frame return value checking

### LINKED ISSUE #55: How to use pop_local_frame(JObject::null())
I would like to call `env.pop_local_frame(JObject::null())`.

The documentation says that "resulting `JObject` can be `NULL` if `result` is `NULL`".
However, in my case `pop_local_frame` returns an `Err(NullPtr("PopLocalFrame result"))`.

Shouldn't the result be `Ok(something)`, since it's an expected behaviour?

### PR DESCRIPTION
**Pull request by DarkEld3r**
Closes #55.

### CODE REVIEW

File: src/wrapper/jnienv.rs [hunk 1]
```diff
@@ -325,7 +325,7 @@ impl<'a> JNIEnv<'a> {
     ///
     /// Note that resulting `JObject` can be `NULL` if `result` is `NULL`.
     pub fn pop_local_frame(&self, result: JObject) -> Result<JObject> {
-        Ok(jni_call!(self.internal, PopLocalFrame, result.into_inner()))
+        Ok(jni_non_null_call!(self.internal, PopLocalFrame, result.into_inner()).into())
```
Comment (dmitry-timofeev) [inline src/wrapper/jnienv.rs]: Shall we use `jni_non_null_call` which checks if any exceptions has occurred for a _safe_ [`PopLocalFrame`](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#PopLocalFrame) (= a method that does not throw exceptions, according to the spec)?

**Comment by DarkEld3r** [comment]
Finally fixed. :sweat_smile:
